### PR TITLE
Enhancement on the categories page

### PR DESCRIPTION
**Pull request by meghanasharathd**

### CODE REVIEW

**Review by dharanichandra1 — COMMENTED** [review]
Background looks broken and pixelated probably the resolution isn't right

**Review by SNSum — APPROVED** [review]

**Comment by SNSum** [comment]
Please check the alignments.

**Comment by meghanasharathd** [comment]
> Background looks broken and pixelated probably the resolution isn't right



> Background looks broken and pixelated probably the resolution isn't right

This will be picked as another git issue as part of the next sprint

**Comment by meghanasharathd** [comment]
> Please check the alignments.

This will be picked as another git issue as part of the next sprint

**Comment by meghanasharathd** [comment]
> > Please check the alignments.
> 
> This will be picked as another git issue as part of the next sprint

**Comment by meghanasharathd** [comment]
> > Please check the alignments.
> 
> This will be picked as another git issue as part of the next sprint

**Review by adtsim — APPROVED** [review]

**Review by dharanichandra1 — APPROVED** [review]

**Pull request merged**
